### ISSUE TITLE
[Feature Request] Fire event when people pick sides during veto process

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/get5-webapi#18]
Can we get a display of what sides did the teams chose on the match page in picking formats?
![image](https://user-images.githubusercontent.com/26146502/117576176-19b19580-b0e5-11eb-8508-34d3434a94cb.png)

**Comment by PhlexPlexico** [comment]
Looks like `Get5_OnSidePicked` does exist which has the following values `team=%d, map=%s, side=%d`

Where team is the enum for teams, match is a string, and side is an int, which seems to be the following enums from sourcepawn:
```
#define CS_TEAM_NONE        0   /**< No team yet. */
#define CS_TEAM_SPECTATOR   1  /**< Spectators. */
#define CS_TEAM_T       2 /**< Terrorists. */
#define CS_TEAM_CT      3 /**< Counter-Terrorists. */ 
```

**Comment by PhlexPlexico** [comment]
When the Util+Knife stats get pushed into get5, this will also be included in the new plugin. Then the API and front end will have to be updated to reflect these changes as well.

**Comment by PhlexPlexico** [comment]
These changes will also be pushed in when there is a new update to the stats as well, since it seemed to fit best there. It will be bundled in with the 1.3.0 release (when additional stats are included) for the API. The front-end will just show an additional sub-table in the veto list if there exists the side selection. I'm not exactly sure how it handles those on "default" sides without picking.

**Comment by kubo6472** [comment]
> 
> 
> When the Util+Knife stats get pushed into get5, this will also be included in the new plugin. Then the API and front end will have to be updated to reflect these changes as well.

Tried compiling it myself from the knife util dmg branch and am getting this error:
```
SourcePawn Compiler 1.10.0.6502
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

.\G5WS.sp(398) : warning 219: local variable "side" shadows a variable at a preceding level
.\G5WS.sp(401) : warning 217: loose indentation
.\G5WS.sp(402) : warning 217: loose indentation
.\G5WS.sp(403) : error 033: array must be indexed (variable "side")
.\G5WS.sp(405) : error 033: array must be indexed (variable "side")

2 Errors.
```

**Comment by PhlexPlexico** [comment]
https://github.com/PhlexPlexico/get5-webapi/blob/5885adba63e10f09ca39de36c26587a66c95c3e5/scripting/G5WS.sp#L398


Clearly surpassed ballmers peak there. Will fix when I get a chance!

**Comment by PhlexPlexico** [comment]
Fixed! :)

**Comment by kubo6472** [comment]
Aight, I broke my G5V, since that version with the sides does not include my PR and therefore the patch for the default/standard veto type

**Comment by PhlexPlexico** [comment]
If you wanted to, you should be able to merge master back into that request and then build. I think that could work! I'm just wary of moving things forward without the get5 support because I'm unsure if the includes files mismatching will be an issue.

**Comment by PhlexPlexico** [comment]
@kubo6472  I merged master back into `util-knife-dmg` in G5V, so you should be able to checkout and test these out if you'd like. If this plugin works and there is no apparent issues with the extra headers/values, I can merge this in along with everything else (G5API stats, G5V stats, and this).

Thanks!

**Comment by kubo6472** [comment]
> Thanks!

No, thank YOU. I'll try this the moment I'll have more energy than from 2 hours of sleep.
