### ISSUE TITLE
[FEATURE REQUEST] Add Compression again and add 7Z Executable Condition

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-webapi#2]
It seems Compression has been fixed after the update of System2 recently. Also system2 has support to check 7Zip and force 32bit version if 64 bit version is missing. Can you add that condition also to make it support better. People have to be sure to give permission to 7z to execute with 775 and have same user access in order to write compressed file in the directory.

**Comment by PhlexPlexico** [comment]
Where are you seeing this? System2 hasn't been updated since 2018. The issue wasn't 7zip not working, the issue was not determining the correct file-size and failing to upload the file.

**Comment by TandelK** [comment]
Oh yeah my bad i did see it the date of update on Alliedmodders just ready 6-12 so thought it was 2019. Yup seems to be that same error for me when i tried again using it. closing it
