### ISSUE TITLE
 sm-ripext 1.3.0

### ISSUE THREAD

**Issue by thewickerman22** [PhlexPlexico/get5-webapi#20]
Deprecated HTTPClient methodmap
Introduced HTTPRequest methodmap
pls update if possible

**Comment by PhlexPlexico** [comment]
Check the utility-knife-dmg branch. That has the new requests implemented but please note there are currently issues with POST data not being sent.

Just because it's deprecated right now doesn't mean you can't use it. I would much rather switch over when everything is 100% stable :)

Thanks!

**Comment by thewickerman22** [comment]
thanks for the reply

**Comment by thewickerman22** [comment]
i have tried compling with the branch u said but i m getting compilation errors. i will give another try

**Comment by PhlexPlexico** [comment]
The only warning I was getting was teh sHHTPTags was unused?

**Comment by thewickerman22** [comment]
ok the plugin is compiled thanks

**Comment by thewickerman22** [comment]
G5WS.smx (G5WS - Get5 Web Stats): Native "HTTPRequest.HTTPRequest" was not found getting this error

**Comment by PhlexPlexico** [comment]
Did you include the natives and source from rest in pawn when compiling? That just means you're missing the library/source from it when trying to compile. Please ensure your sourcemod installation has the source for Rest in Pawn

**Comment by PhlexPlexico** [comment]
For more info you can see how GitHub actions compiles this here https://github.com/PhlexPlexico/get5-webapi/blob/utility-knife-dmg/.github/workflows/make_release.yml

**Comment by thewickerman22** [comment]
i m compiling in windows. i have included the latest sm source as well as RIP. do i need anythin extra for compiling

**Comment by PhlexPlexico** [comment]
Did you include Ripext on your Windows server in `addons/sourcemod/extensions` or whichever directory it should be in?

**Comment by thewickerman22** [comment]
yes i did

**Comment by thewickerman22** [comment]
![1](https://user-images.githubusercontent.com/69313521/121831024-157c2780-cce4-11eb-9a11-a412d218a2ed.jpg)

**Comment by thewickerman22** [comment]
did for 64-bit also

**Comment by PhlexPlexico** [comment]
`sm extensions list` in your game server. Does rest in pawn appear!

**Comment by thewickerman22** [comment]
yea

**Comment by thewickerman22** [comment]
![1](https://user-images.githubusercontent.com/69313521/121831442-13ff2f00-cce5-11eb-8adb-63a1591dd130.jpg)

**Comment by thewickerman22** [comment]
![2](https://user-images.githubusercontent.com/69313521/121831535-532d8000-cce5-11eb-809d-ce6168b73e15.jpg)

**Comment by PhlexPlexico** [comment]
1.1.1? You need 1.3. httprequest was just implemented in 1.3, not 1.1.1.

**Comment by thewickerman22** [comment]
ok my bad sorry

**Comment by PhlexPlexico** [comment]
No worries! But please note that there are currently potential [issues](https://github.com/PhlexPlexico/G5API/issues/103) surrounding this plugin/RiP and windows servers. If you run into updates not being sent across, this may be the case.

**Comment by thewickerman22** [comment]
ok

**Comment by thewickerman22** [comment]
it is possible to use steamworks instead of RIP

**Comment by PhlexPlexico** [comment]
The reason I chose ripext over Steamworks was because I am able to send an octet stream over HTTP, which allows demo uploads once a match finishes. If you want to use the old plugin, the API should be compatible with the old plugin as well, since I tried to keep it backwards compatible. But you will lose functionality such as demo uploads, veto picks, and side picks.
