### ISSUE TITLE
sm-json v3.0 implmenetation ?

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-webapi#3]
With the current update of sm-json v3.0 Splewis get5 was recently updated today. It seems that it has broken the plugin with new json format being used. Can you check the same ?

**Comment by PhlexPlexico** [comment]
Please grab latest master branch and recompile. Tell me if that fixes it.

**Comment by PhlexPlexico** [comment]
Haven't heard anything back but since I did throw some of the replacement code in the jsonhelpers.sp, I don't think there should be any issue now.

**Comment by TandelK** [comment]
It was recently updated , We have issue with jsonhelper recently so today there was a small update which is still pending in Pull Request. It used to show 22 Maps for 7 Maps in Veto and other location as it was bugged.
